# Generated by Django 4.0.1 on 2022-01-27 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Amount')),
                ('deposited_by', models.CharField(default='', max_length=255, null=True, verbose_name='Deposited By')),
                ('deposited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deposited At')),
                ('withdrawn_by', models.CharField(default='', max_length=255, null=True, verbose_name='Withdrawn By')),
                ('withdrawn_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Withdrawn At')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Data',
                'verbose_name_plural': 'Transaction Data',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_id', models.TextField(default='', null=True, verbose_name='Wallet ID')),
                ('wallet_name', models.TextField(blank=True, default='', null=True, verbose_name='Wallet Name')),
                ('enabled_status', models.BooleanField(default=True, verbose_name='Enabled Status')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Enabled At')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Disabled At')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_wallet_app.transaction_data')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_id', models.TextField(default='', null=True, verbose_name='Customer ID')),
                ('auth_token', models.TextField(default='', null=True, verbose_name='Auth Token')),
                ('name', models.CharField(default='', max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(default='', max_length=255, null=True, verbose_name='Email')),
                ('hashed_password', models.TextField(default='', null=True, verbose_name='Hashed Password')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_wallet', models.ManyToManyField(blank=True, related_name='user_wallet', to='test_wallet_app.Wallet', verbose_name="User's Wallet")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
