# Generated by Django 4.0.1 on 2022-01-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_data',
        ),
        migrations.AddField(
            model_name='transaction_data',
            name='transaction_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test_wallet_app.wallet'),
        ),
    ]
