# Generated by Django 4.0.1 on 2022-01-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_wallet_app', '0003_alter_transaction_data_deposited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='deposited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposited_by', to='test_wallet_app.user', verbose_name='Deposited By'),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_by', to='test_wallet_app.user', verbose_name='Withdrawn By'),
        ),
    ]
