# Generated by Django 4.0.1 on 2022-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_wallet_app', '0005_alter_transaction_data_deposited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_data',
            name='reference_id',
            field=models.TextField(default=None, max_length=255, unique=True, verbose_name='Deposited By'),
        ),
    ]
