# Generated by Django 4.0.1 on 2022-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_wallet_app', '0006_transaction_data_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deposited At'),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Withdrawn At'),
        ),
    ]
